# Generated by Django 5.2.1 on 2025-05-21 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=100)),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('numero_pisos', models.PositiveSmallIntegerField(default=1)),
                ('total_asientos', models.PositiveIntegerField()),
            ],
        ),
    ]
