# Generated by Django 5.2.1 on 2025-05-22 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=10),
        ),
        migrations.AlterField(
            model_name='compra',
            name='fecha_compra',
            field=models.DateField(auto_now_add=True),
        ),
    ]
