# Generated by Django 5.2.1 on 2025-05-21 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pasajero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=8, unique=True)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('permiso_notarial', models.ImageField(blank=True, null=True, upload_to='permisos/')),
                ('es_menor', models.BooleanField(default=False, editable=False)),
                ('acompaniante_dni', models.CharField(blank=True, max_length=8, null=True)),
            ],
        ),
    ]
